<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('payments', function (Blueprint $table) {
            $table->id();
            $table->foreignId('student_exam_id')->constrained('student_exams')->onDelete('cascade');
            $table->string('payment_id')->nullable(); // Unique Payment ID generated by PayHere for the processed payment
            $table->decimal('payhere_amount', 10, 2)->nullable(); // Total Amount of the payment
            $table->string('payhere_currency', 10)->nullable(); // Currency code of the payment (LKR/USD/GBP/EUR/AUD)
            $table->integer('status_code')->nullable(); // Payment status code (2, 0, -1, -2, -3)
            $table->string('md5sig')->nullable(); // Encrypted signature to verify the payment
            $table->string('method', 32)->nullable(); // Payment method selected by the customer. (VISA, MASTER, AMEX, EZCASH, MCASH, GENIE, VISHWA, PAYAPP, HNB, FRIMI)
            $table->string('status_message')->nullable(); // Message received from payment gateway which the customer tried to pay
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('payments');
    }
};
